### ISSUE TITLE
Fails on install.

### ISSUE THREAD

**Issue by pcwd** [vazw/siamstr#1]
lightning@node:~/nostr-address-provider$ npx tailwindcss -i ./input.css -o ./style/output.css --watch

/home/lightning/nostr-address-provider/node_modules/postcss-load-config/node_modules/lilconfig/src/index.js:161
        } = getOptions(name, options ?? {}, false);
                                      ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/lightning/nostr-address-provider/node_modules/postcss-load-config/src/index.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
lightning@node:~/nostr-address-provider$

**Comment by pcwd** [comment]
npm was the wrong verson.
